<?php

function ean_menu()
{
    $query = "select nid from node where type='menu'";
    $records = db_query($query);
    $items = array();
    $page_arguments = array();
    foreach ($records as $record) {
        $node = node_load($record->nid);
        if (!empty($node->field_page_arguments['und'])) {
            $page_arguments = explode(",", $node->field_page_arguments['und'][0]['value']);
        }
        $items[$node->field_url['und'][0]['value']] = array(
            'title' => $node->title,
            'access callback' => TRUE,
            'page callback' => $node->field_page_callback['und'][0]['value'],
            'page arguments' => $page_arguments,
            'file' => $node->field_file['und'][0]['value'],
        );
    }
    return $items;
}

function ean_theme()
{
    return array(
       'hotel' => array(
            'template' => 'hotel',
            'path' => 'sites/all/modules/custom/ean',
            'variables' => array('title' => '', 'contents' => array())
        ),
    );
}

function ean_menu_alter(&$items)
{
    // Removing certain local navigation tabs that are either undesired or need to be custom relocated.

    // Set these tabs to MENU_CALLBACK, so they still register the path, but just don't show the tab:
    $items['node/%node/edit']['type'] = MENU_CALLBACK;
    $items['node/%node/moderation']['type'] = MENU_CALLBACK;
    $items['node/%node']['type'] = MENU_CALLBACK;
    $items['user']['type'] = MENU_CALLBACK;
    $items['user/password']['type'] = MENU_CALLBACK;
    $items['user/register']['type'] = MENU_CALLBACK;


}

function ean_form_alter(&$form, &$form_state, $form_id)
{
    global $user;
    if ($user->uid == 1) {
        return;
    }

    $forms = array(
        "brief1_node_form",
        "brief2_node_form",
        "brief3_node_form",
        "brief4_node_form",
        "brief5_node_form",
    );
    $states = array(
        "artifacts_under_review",
        "approved_briefs",
        "briefs_under_review",
        "approved_artifacts",
        "artifacts_to_ammend",
        "approved_artifacts",
    );

    $content_type = str_replace("_node_form", "", $form_id);
    $dsm_fields = array_keys(field_info_instances("node", $content_type));

    if (in_array($form_id, $forms)) {
        $subject = request_path();
        $pattern = '/node\/[0-9]+\/edit/';
        $result = preg_match($pattern, $subject);
        if ($result) {
            $nid = str_replace("/edit", "", str_replace("node/", "", $subject));
            $node = node_load($nid);
            if (in_array($node->workbench_moderation["current"]->state, $states)) {
                $form["title"]["#access"] = 0;
                $form["workbench_access"]["#access"] = 0;
                foreach ($dsm_fields as $dsm_field) {
                    $form[$dsm_field]["#access"] = 0;
                }
                if (in_array("customer", $user->roles)) {
                    $form["field_brief_attachments"]["#access"] = 1;

                }
                if (in_array("editor", $user->roles)) {
                    $form["field_artifact_attachment"]["#access"] = 1;
                }
            };

        }
        $form["actions"]["preview"]["#access"] = 0;
    }
}
